/**
 * The Agent Headquarters floor, rendered against a real firm.
 *
 * The fixture is six desks and four runs, generated by `agentFloorFixture.pg.test.ts`
 * from a run against PostgreSQL. Hand-written desks would prove the page draws
 * cards; they would not prove it draws the firm that exists.
 *
 * The governing rule, the same one the case surfaces are held to: if two
 * institutional states would lead a reader to do different things, they must
 * not render the same. Here that means a rejected run and a failed run cannot
 * look alike, and work waiting on a person cannot look like work that is done.
 *
 * And one rule specific to this page, because it replaced a fiction: **nothing
 * may appear that the record does not contain.** The assertions about what is
 * absent — no progress bar, no invented agent — are as load-bearing as the
 * assertions about what is present.
 */

import { render, screen, within } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import {
  RouterProvider,
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
} from '@tanstack/react-router'
import type { ReactNode } from 'react'
import { AgentFloorPage } from './agents.index'
import floor from '~/test/fixtures/agentFloor.mixed.json'
import type { AgentDesk } from '~/application/analysis/agentDirectory'
import type { AgentDirectoryResponse } from '~/infrastructure/analysis/serverFns'
import { RUN_STATE_LABEL } from '~/presentation/analysis/runText'

const desks = floor as unknown as readonly AgentDesk[]

/** A memory router over the two routes the floor links to, and nothing else. */
async function withRouter(ui: ReactNode) {
  const rootRoute = createRootRoute({ component: () => <>{ui}</> })
  const children = [
    createRoute({
      getParentRoute: () => rootRoute,
      path: '/agents/$departmentId',
      component: () => null,
    }),
    createRoute({
      getParentRoute: () => rootRoute,
      path: '/cases/$caseId',
      component: () => null,
    }),
  ]
  const router = createRouter({
    routeTree: rootRoute.addChildren(children),
    history: createMemoryHistory({ initialEntries: ['/'] }),
  })
  await router.load()
  /* eslint-disable-next-line @typescript-eslint/no-explicit-any -- a test tree, not the app's */
  return render(<RouterProvider router={router as any} />)
}

const renderFloor = (entries: readonly AgentDesk[] = desks) =>
  withRouter(<AgentFloorPage response={{ ok: true, desks: entries }} />)

describe('the floor shows the firm that exists', () => {
  it('lists every desk a registered workflow assigns work to', async () => {
    await renderFloor()

    for (const desk of desks) {
      expect(screen.getByRole('link', { name: desk.name })).toBeInTheDocument()
    }
    /*
     * Five runs, not four: the three on Global Macro, the Quant desk's failure,
     * and the Research Office aggregation. The count is read off the records,
     * so it moves when the firm does.
     */
    expect(screen.getByText('6 avdelningar, 5 registrerade körningar.')).toBeInTheDocument()
  })

  it('links each desk to its own page', async () => {
    await renderFloor()

    const hrefs = screen
      .getAllByRole('link')
      .map((node) => node.getAttribute('href'))
      .filter((href): href is string => href !== null && href.startsWith('/agents/'))

    for (const desk of desks) {
      expect(hrefs).toContain(`/agents/${desk.departmentId}`)
    }
  })

  it('marks the control functions without ranking them', async () => {
    await renderFloor()
    /* Three governance desks in the seeded firm's workflow. */
    expect(screen.getAllByText('Kontrollfunktion')).toHaveLength(3)
  })

  it('says a desk with no runs has none, rather than implying activity', async () => {
    await renderFloor()
    /* The three control functions have not run in this fixture. */
    expect(screen.getAllByText('Har inte kört något ännu')).toHaveLength(3)
  })
})

describe('run states never render as one another', () => {
  it('shows a rejection and a failure as different things', async () => {
    await renderFloor()
    const history = screen.getByRole('heading', { name: /^Senaste körningar/ }).closest('section')!

    /*
     * The distinction C2-1 built a run state, a command and a vocabulary to
     * keep. A page that showed both as "something went wrong" would collapse
     * "how often does this desk break" and "how often is its work not good
     * enough" into one number.
     */
    expect(within(history).getByText(RUN_STATE_LABEL.rejected)).toBeInTheDocument()
    expect(within(history).getByText(RUN_STATE_LABEL.failed)).toBeInTheDocument()
    expect(RUN_STATE_LABEL.rejected).not.toBe(RUN_STATE_LABEL.failed)
  })

  it('distinguishes work awaiting a person from work already accepted', async () => {
    await renderFloor()
    const history = screen.getByRole('heading', { name: /^Senaste körningar/ }).closest('section')!

    expect(
      within(history).getByText(RUN_STATE_LABEL['awaiting-acceptance']),
    ).toBeInTheDocument()
    expect(within(history).getAllByText(RUN_STATE_LABEL.completed).length).toBeGreaterThan(0)
  })

  it('says what produced every run, so a stub cannot read as live analysis', async () => {
    await renderFloor()
    const history = screen.getByRole('heading', { name: /^Senaste körningar/ }).closest('section')!

    /* Every run in this fixture is stub work, and every row says so. */
    const rows = within(history).getAllByRole('listitem')
    expect(within(history).getAllByText('Simulerad')).toHaveLength(rows.length)
    expect(within(history).queryByText('Live-modell')).not.toBeInTheDocument()
  })

  it('reports what a run spent, without inventing a cost', async () => {
    await renderFloor()
    /* A stub consumes nothing external, and the record says exactly that. */
    expect(screen.getAllByText('Förbrukade ingenting').length).toBeGreaterThan(0)
  })
})

describe('what the page must never contain', () => {
  it('has no progress indicator anywhere', async () => {
    await renderFloor()
    /*
     * The page this replaced drew a 64%-full bar for an agent that did not
     * exist. A run reports state transitions and never a completion fraction,
     * so any progressbar here would be a number nobody measured.
     */
    expect(screen.queryAllByRole('progressbar')).toHaveLength(0)
  })

  it('contains none of the invented agents it replaced', async () => {
    await renderFloor()
    for (const invented of [
      'Marknadsanalytiker',
      'Portföljagent',
      'Riskagent',
      'Nyhetsagent',
      'Rapportagent',
    ]) {
      expect(screen.queryByText(invented)).not.toBeInTheDocument()
    }
    expect(screen.queryByText(/Simulerade agentkörningar/)).not.toBeInTheDocument()
  })
})

describe('the empty and failed states', () => {
  it('says a firm with no commissionable desks has none', async () => {
    await renderFloor([])
    expect(screen.getByText('Inga avdelningar att tilldela arbete')).toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: /Senaste körningar/ })).not.toBeInTheDocument()
  })

  it('renders a failure as a sentence, never as its code', async () => {
    const failed: AgentDirectoryResponse = { ok: false, code: 'SERVICE_UNAVAILABLE' }
    await withRouter(<AgentFloorPage response={failed} />)

    expect(screen.getByText('Analysmiljön svarar inte just nu.')).toBeInTheDocument()
    expect(screen.queryByText(/SERVICE_UNAVAILABLE|postgres/)).not.toBeInTheDocument()
  })

  it('distinguishes a missing configuration from an unreachable database', async () => {
    await withRouter(<AgentFloorPage response={{ ok: false, code: 'NOT_CONFIGURED' }} />)
    expect(screen.getByText('Analysmiljön saknar databaskonfiguration.')).toBeInTheDocument()
  })
})
