/**
 * The Agent Headquarters floor, rendered against a real firm.
 *
 * The fixture is six desks and four runs, generated by `agentFloorFixture.pg.test.ts`
 * from a run against PostgreSQL. Hand-written desks would prove the page draws
 * cards; they would not prove it draws the firm that exists.
 *
 * The governing rule, the same one the case surfaces are held to: if two
 * institutional states would lead a reader to do different things, they must
 * not render the same. Here that means a rejected run and a failed run cannot
 * look alike, and work waiting on a person cannot look like work that is done.
 *
 * And one rule specific to this page, because it replaced a fiction: **nothing
 * may appear that the record does not contain.** The assertions about what is
 * absent — no progress bar, no invented agent — are as load-bearing as the
 * assertions about what is present.
 */

import { render, screen, within } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import {
  RouterProvider,
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
} from '@tanstack/react-router'
import type { ReactNode } from 'react'
import { HeadquartersPage } from './headquarters'
import { commandCenterView } from '~/application/analysis/commandCenter'
import floor from '~/test/fixtures/agentFloor.mixed.json'
import type { AgentDesk } from '~/application/analysis/agentDirectory'
import type { AgentDirectoryResponse } from '~/infrastructure/analysis/serverFns'
import { RUN_STATE_LABEL } from '~/presentation/analysis/runText'

const desks = floor as unknown as readonly AgentDesk[]

/**
 * The Command Center view over a set of desks.
 *
 * The floor is projected by the application read model rather than assembled
 * here, so these suites are held to the same counting the product does — a
 * hand-built view would let the page pass against numbers the firm never
 * produced.
 */
const viewOf = (entries: readonly AgentDesk[]) =>
  commandCenterView({
    cases: [],
    desks: entries,
    activity: [],
    evidenceSetCount: 0,
    latestAssemblyAt: null,
  })

/** A memory router over the two routes the floor links to, and nothing else. */
async function withRouter(ui: ReactNode) {
  const rootRoute = createRootRoute({ component: () => <>{ui}</> })
  const children = [
    createRoute({
      getParentRoute: () => rootRoute,
      path: '/agents/$departmentId',
      component: () => null,
    }),
    createRoute({
      getParentRoute: () => rootRoute,
      path: '/cases/$caseId',
      component: () => null,
    }),
  ]
  const router = createRouter({
    routeTree: rootRoute.addChildren(children),
    history: createMemoryHistory({ initialEntries: ['/'] }),
  })
  await router.load()
  /* eslint-disable-next-line @typescript-eslint/no-explicit-any -- a test tree, not the app's */
  return render(<RouterProvider router={router as any} />)
}

/*
 * The floor moved into `/headquarters` when the Command Center v1 gate merged
 * the desk directory and the case list into one investment floor. These
 * assertions did not move with it by accident — they are the rules that keep
 * the page from drawing a firm that does not exist, and they are retargeted
 * rather than rewritten.
 *
 * The case half is supplied empty here: this file is about the desks.
 */
const renderFloor = (entries: readonly AgentDesk[] = desks) =>
  withRouter(
    <HeadquartersPage
      center={{ ok: true, view: viewOf(entries) }}
      cases={{ ok: true, cases: [] }}
    />,
  )

describe('the floor shows the firm that exists', () => {
  it('lists every desk a registered workflow assigns work to', async () => {
    await renderFloor()

    for (const desk of desks) {
      /*
       * Asserted on the href: a desk tile's accessible name is its whole
       * content — name, manager and workload — because the tile IS the link
       * into the workspace, and the desk's name also appears on the run rows
       * beneath. What must hold is that the floor offers a way in.
       */
      const hrefs = screen.getAllByRole('link').map((link) => link.getAttribute('href'))
      expect(hrefs).toContain(`/agents/${desk.departmentId}`)
    }
    /*
     * The counts are asserted where they live, not on a page-title strip.
     *
     * That strip repeated them above the workstation and was removed: the floor
     * states its own composition, and the run ledger states its own count. Five
     * runs, not four — the three on Global Macro, the Quant desk's failure, and
     * the Research Office aggregation. The count is read off the records, so it
     * moves when the firm does.
     */
    expect(screen.getByText(/deskar · .* kontrollfunktioner/)).toBeInTheDocument()

    const ledger = screen
      .getAllByRole('heading', { name: /^Senaste körningar/ })[0]!
      .closest('section')!
    expect(within(ledger).getByText('5')).toBeInTheDocument()
  })

  it('links each desk to its own page', async () => {
    await renderFloor()

    const hrefs = screen
      .getAllByRole('link')
      .map((node) => node.getAttribute('href'))
      .filter((href): href is string => href !== null && href.startsWith('/agents/'))

    for (const desk of desks) {
      expect(hrefs).toContain(`/agents/${desk.departmentId}`)
    }
  })

  it('marks the control functions without ranking them', async () => {
    await renderFloor()
    /*
     * One band, labelled and counted, rather than a badge repeated on each
     * tile. The separation is what must hold; three governance desks in the
     * seeded firm's workflow sit inside it, and none of them is rendered
     * smaller or beneath the desks it reviews.
     */
    const band = screen.getByText('Oberoende kontrollfunktioner').parentElement!
    expect(band).toHaveTextContent('3')
    expect(screen.getByText('Specialistdeskar')).toBeInTheDocument()
  })

  it('implies no activity about any desk, in either direction', async () => {
    await renderFloor()
    /*
     * The floor used to print `har aldrig kort` on every desk that had not run.
     * The plates no longer carry run history at all: it moved to the desk's own
     * workspace, which states the fact in full and adds what it does not mean.
     *
     * **The rule that statement existed to protect still holds here**, and it is
     * what this asserts: nothing on the floor may suggest a desk is working. No
     * status light, no AKTIV, no LIVE. The reference's row of green pills is the
     * fabrication this surface refuses, and a plate that says nothing about
     * execution cannot be misread as saying something about it.
     *
     * Scoped to the floor, because `Institutionell aktivitet` is a real region
     * reporting persisted events and is entitled to the word.
     */
    const floor = screen
      .getByRole('heading', { name: /^Investment Floor/ })
      .closest('section')!
    for (const forbidden of [/aktiv/i, /live/i, /arbetar/i]) {
      expect(within(floor).queryAllByText(forbidden)).toEqual([])
    }
    expect(screen.queryByRole('progressbar')).not.toBeInTheDocument()
  })
})

describe('run states never render as one another', () => {
  it('shows a rejection and a failure as different things', async () => {
    await renderFloor()
    const history = screen
      .getByRole('heading', { name: /^Senaste körningar/ })
      .closest('section')!

    /*
     * The distinction C2-1 built a run state, a command and a vocabulary to
     * keep. A page that showed both as "something went wrong" would collapse
     * "how often does this desk break" and "how often is its work not good
     * enough" into one number.
     */
    expect(within(history).getByText(RUN_STATE_LABEL.rejected)).toBeInTheDocument()
    expect(within(history).getByText(RUN_STATE_LABEL.failed)).toBeInTheDocument()
    expect(RUN_STATE_LABEL.rejected).not.toBe(RUN_STATE_LABEL.failed)
  })

  it('distinguishes work awaiting a person from work already accepted', async () => {
    await renderFloor()
    const history = screen
      .getByRole('heading', { name: /^Senaste körningar/ })
      .closest('section')!

    expect(
      within(history).getByText(RUN_STATE_LABEL['awaiting-acceptance']),
    ).toBeInTheDocument()
    expect(
      within(history).getAllByText(RUN_STATE_LABEL.completed).length,
    ).toBeGreaterThan(0)
  })

  it('says what produced every run, so a stub cannot read as live analysis', async () => {
    await renderFloor()
    const history = screen
      .getByRole('heading', { name: /^Senaste körningar/ })
      .closest('section')!

    /* Every run in this fixture is stub work, and every row says so. */
    const rows = within(history).getAllByRole('listitem')
    expect(within(history).getAllByText('Simulerad')).toHaveLength(rows.length)
    expect(within(history).queryByText('Live-modell')).not.toBeInTheDocument()
  })

  it('reports what a run spent, without inventing a cost', async () => {
    await renderFloor()
    /* A stub consumes nothing external, and the record says exactly that. */
    expect(screen.getAllByText('Förbrukade ingenting').length).toBeGreaterThan(0)
  })
})

describe('what the page must never contain', () => {
  it('has no progress indicator anywhere', async () => {
    await renderFloor()
    /*
     * The page this replaced drew a 64%-full bar for an agent that did not
     * exist. A run reports state transitions and never a completion fraction,
     * so any progressbar here would be a number nobody measured.
     */
    expect(screen.queryAllByRole('progressbar')).toHaveLength(0)
  })

  it('contains none of the invented agents it replaced', async () => {
    await renderFloor()
    for (const invented of [
      'Marknadsanalytiker',
      'Portföljagent',
      'Riskagent',
      'Nyhetsagent',
      'Rapportagent',
    ]) {
      expect(screen.queryByText(invented)).not.toBeInTheDocument()
    }
    expect(screen.queryByText(/Simulerade agentkörningar/)).not.toBeInTheDocument()
  })
})

describe('the empty and failed states', () => {
  it('says a firm with no commissionable desks has none', async () => {
    await renderFloor([])
    expect(screen.getByText('Inga avdelningar att tilldela arbete')).toBeInTheDocument()
    /* No desks means no desk cards — and nothing standing in for them. */
    expect(screen.queryByRole('link', { name: /Global Macro/ })).not.toBeInTheDocument()
  })

  it('renders a failure as a sentence, never as its code', async () => {
    const failed: AgentDirectoryResponse = { ok: false, code: 'SERVICE_UNAVAILABLE' }
    await withRouter(<HeadquartersPage center={failed} cases={{ ok: true, cases: [] }} />)

    expect(screen.getByText('Analysmiljön svarar inte just nu.')).toBeInTheDocument()
    expect(screen.queryByText(/SERVICE_UNAVAILABLE|postgres/)).not.toBeInTheDocument()
  })

  it('distinguishes a missing configuration from an unreachable database', async () => {
    await withRouter(
      <HeadquartersPage
        center={{ ok: false, code: 'NOT_CONFIGURED' }}
        cases={{ ok: true, cases: [] }}
      />,
    )
    expect(
      screen.getByText('Analysmiljön saknar databaskonfiguration.'),
    ).toBeInTheDocument()
  })
})
