/**
 * The Headquarters queue, rendered against a real queue.
 *
 * The fixture is three cases in three institutional states, generated by
 * `caseListFixture.pg.test.ts` from a run against PostgreSQL. A queue of
 * hand-written rows would prove the page draws a list; it would not prove the
 * page draws what the firm is actually holding.
 *
 * The same governing rule as the case page: if two institutional states would
 * lead a reader to do different things, they must not render the same. Here
 * that means a settled case and a case waiting on somebody cannot appear in
 * the same section, and cannot show the same owner.
 */

import { render, screen, within } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import {
  RouterProvider,
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
} from '@tanstack/react-router'
import type { ReactNode } from 'react'
import { HeadquartersPage } from './headquarters'
import { commandCenterView } from '~/application/analysis/commandCenter'
import type { AgentDesk } from '~/application/analysis/agentDirectory'
import mixed from '~/test/fixtures/caseList.mixed.json'
import type { CaseListing } from '~/application/analysis/caseListing'
import type { CaseListResponse } from '~/infrastructure/analysis/serverFns'
import { ACT_LABEL, STAGE_LABEL } from '~/presentation/analysis/caseStandingText'

const cases = mixed as unknown as readonly CaseListing[]

/**
 * The Command Center view over a set of desks.
 *
 * The floor is projected by the application read model rather than assembled
 * here, so these suites are held to the same counting the product does — a
 * hand-built view would let the page pass against numbers the firm never
 * produced.
 */
const viewOf = (entries: readonly AgentDesk[]) =>
  commandCenterView({
    cases: [],
    desks: entries,
    activity: [],
    evidenceSetCount: 0,
    latestAssemblyAt: null,
  })

/**
 * A router, because the queue links to cases and `Link` needs one.
 *
 * A memory router over a two-route tree rather than the generated one: this
 * suite is about what the queue renders, and pulling in every route in the app
 * would make an unrelated page's loader a reason for this test to fail.
 *
 * The `/cases/$caseId` route exists so the links resolve to real hrefs — a stub
 * that swallowed the path would let a broken link pass.
 */
async function withRouter(ui: ReactNode) {
  const rootRoute = createRootRoute({ component: () => <>{ui}</> })
  const caseRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/cases/$caseId',
    component: () => null,
  })
  const deskRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/agents/$departmentId',
    component: () => null,
  })
  const router = createRouter({
    routeTree: rootRoute.addChildren([caseRoute, deskRoute]),
    history: createMemoryHistory({ initialEntries: ['/'] }),
  })
  /*
   * Awaited: the provider resolves its first match asynchronously, and
   * rendering without waiting produces an empty document that every assertion
   * below would fail against for the wrong reason.
   */
  /* eslint-disable-next-line @typescript-eslint/no-explicit-any -- a test tree, not the app's */
  await router.load()
  /* eslint-disable-next-line @typescript-eslint/no-explicit-any -- a test tree, not the app's */
  return render(<RouterProvider router={router as any} />)
}

/*
 * The queue moved into `/headquarters` when the Command Center v1 gate merged
 * the desk floor and the case list into one investment floor. These assertions
 * came with it: what they protect — that a settled case and a case waiting on
 * somebody never render alike — is a property of the queue, not of the route it
 * happened to live on.
 *
 * The desk half is supplied empty; this file is about the work.
 */
const renderQueue = (entries: readonly CaseListing[] = cases) =>
  withRouter(
    <HeadquartersPage
      center={{ ok: true, view: viewOf([]) }}
      cases={{ ok: true, cases: entries }}
    />,
  )

const card = (heading: RegExp) =>
  screen.getByRole('heading', { name: heading }).closest('section')!

describe('the queue leads with what is owed', () => {
  it('separates outstanding work from settled work', async () => {
    await renderQueue()

    /*
     * Two sections, not one list. A single list ordered by date buries the work
     * somebody owes underneath the work already finished, which is the opposite
     * of what a queue is for.
     */
    expect(screen.getByRole('heading', { name: /^Pågående \(2\)$/ })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: /^Avgjorda \(1\)$/ })).toBeInTheDocument()
  })

  it('states the case counts on the queue itself, not on a title strip', async () => {
    await renderQueue()
    /*
     * The page-title strip that used to repeat these counts above the
     * workstation is gone. The counts belong to the sections that hold the
     * cases, and asserting the strip's absence keeps it from coming back: a
     * figure printed twice is a figure that can disagree with itself.
     */
    expect(screen.getByRole('heading', { name: /^Pågående \(2\)$/ })).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: /^Avgjorda \(1\)$/ })).toBeInTheDocument()
    expect(screen.queryByText(/registrerade körningar/)).not.toBeInTheDocument()
  })

  it('links every case to its own page', async () => {
    await renderQueue()

    /*
     * By href, not by text. The harness gives every generated case the same
     * question, so matching on it would find three rows — and a queue where
     * two rows linked to one case is exactly the defect this should catch.
     */
    const links = screen.getAllByRole('link').map((node) => node.getAttribute('href'))
    for (const entry of cases) {
      expect(links).toContain(`/cases/${entry.investmentCase.id}`)
    }
    expect(new Set(links).size).toBe(cases.length)
  })

  it('shows a stage and a next act on every row', async () => {
    await renderQueue()
    for (const entry of cases) {
      /* Every row carries both, so no row is a bare identifier. */
      expect(
        screen.getAllByText(STAGE_LABEL[entry.standing.stage]).length,
      ).toBeGreaterThan(0)
      expect(
        screen.getAllByText(ACT_LABEL[entry.standing.nextAct.act]).length,
      ).toBeGreaterThan(0)
    }
  })
})

describe('ownership never renders the same for settled and outstanding', () => {
  it('names nobody on a decided case, in words', async () => {
    await renderQueue()
    const settled = card(/^Avgjorda \(1\)$/)

    expect(within(settled).getByText('Ingen ansvarig — avgjort')).toBeInTheDocument()
    expect(within(settled).getByText(/Inget utestående/)).toBeInTheDocument()
    /* And no outstanding-step count, because there are none. */
    expect(within(settled).queryByText(/utestående steg/)).not.toBeInTheDocument()
  })

  it('names the chief on a case awaiting decision', async () => {
    await renderQueue()
    const pending = card(/^Pågående \(2\)$/)

    expect(within(pending).getByText('Ansvarig: cio')).toBeInTheDocument()
    expect(within(pending).getByText('Fatta beslut eller återsänd')).toBeInTheDocument()
  })

  it('shows the desk and the outstanding count on work still in governance', async () => {
    await renderQueue()
    const pending = card(/^Pågående \(2\)$/)

    expect(within(pending).getByText('Registrera faktagranskning')).toBeInTheDocument()
    expect(within(pending).getAllByText(/utestående steg/).length).toBeGreaterThan(0)
  })
})

describe('the empty and failed states', () => {
  it('says a firm holding nothing is holding nothing, not that something broke', async () => {
    await renderQueue([])
    expect(screen.getByText('Inga ärenden ännu')).toBeInTheDocument()
    /* No sections at all — an empty "Pågående (0)" would read as a lost list. */
    expect(screen.queryByRole('heading', { name: /^Pågående/ })).not.toBeInTheDocument()
  })

  it('renders a failure as a sentence, never as its code', async () => {
    const failed: CaseListResponse = { ok: false, code: 'SERVICE_UNAVAILABLE' }
    await withRouter(
      <HeadquartersPage center={{ ok: true, view: viewOf([]) }} cases={failed} />,
    )

    expect(screen.getByText('Analysmiljön svarar inte just nu.')).toBeInTheDocument()
    expect(screen.queryByText(/SERVICE_UNAVAILABLE|postgres/)).not.toBeInTheDocument()
  })

  it('distinguishes a missing configuration from an unreachable database', async () => {
    /*
     * Different obligations: one is a deployment that was never finished, the
     * other is a database to go and look at. Same blank page for both would
     * send an operator to the wrong place.
     */
    await withRouter(
      <HeadquartersPage
        center={{ ok: true, view: viewOf([]) }}
        cases={{ ok: false, code: 'NOT_CONFIGURED' }}
      />,
    )
    expect(
      screen.getByText('Analysmiljön saknar databaskonfiguration.'),
    ).toBeInTheDocument()
  })
})
