/**
 * The pixels, proved against records the institution actually produced.
 *
 * Every fixture rendered here was generated by `caseOverviewFixture.pg.test.ts`
 * from a case driven through the whole workflow against PostgreSQL. Nothing
 * below is hand-written institutional data, which is the point: a render test
 * against an invented object proves the page draws *something*, not that it
 * draws the firm.
 *
 * ## What is being checked
 *
 * That the human-visible representation preserves the distinctions the read
 * model spent five stages earning. The governing rule:
 *
 *   *If two institutional states would lead to different obligations, they must
 *   not render as the same visual state.*
 *
 * A mapping or a component is the easiest place to quietly undo that — one
 * shared green tick and `not-applicable` becomes `complete` on screen while
 * every other layer still knows the difference.
 */

import { render, screen, within } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import { CaseOverviewPage } from './cases.$caseId'
import decided from '~/test/fixtures/caseOverview.decided.json'
import awaiting from '~/test/fixtures/caseOverview.awaiting.json'
import inflight from '~/test/fixtures/caseOverview.inflight.json'
import noRisk from '~/test/fixtures/caseOverview.noRisk.json'
import reconsidered from '~/test/fixtures/caseOverview.reconsidered.json'
import type { CaseOverview } from '~/application/analysis/caseOverview'
import type { CaseOverviewResponse } from '~/infrastructure/analysis/serverFns'

/*
 * JSON has no idea about the union arms, and re-deriving the type here would be
 * a second declaration of the read model. The fixture is generated FROM that
 * type by a test that fails when it drifts, so the cast is checked elsewhere
 * rather than assumed here.
 */
const asOverview = (fixture: unknown) => fixture as unknown as CaseOverview
const ok = (fixture: unknown): CaseOverviewResponse => ({
  ok: true,
  overview: asOverview(fixture),
})

const renderCase = (fixture: unknown) =>
  render(<CaseOverviewPage response={ok(fixture)} />)

/** The card a section lives in, so an assertion cannot match a neighbour. */
const card = (heading: RegExp) =>
  screen.getByRole('heading', { name: heading }).closest('section')!

/* ------------------------------------------------- the twelve institutional items */

describe('a decided case shows every institutional item', () => {
  it('leads with the question, not with the data', () => {
    renderCase(decided)
    expect(
      screen.getByRole('heading', { name: /Does the ECB cut before Q2\?/ }),
    ).toBeInTheDocument()
  })

  it('renders the standing panel above the record', () => {
    renderCase(decided)
    /* Läge, ansvarig, nästa steg — the three answers a reader needs first. */
    expect(screen.getByText('Läge')).toBeInTheDocument()
    expect(screen.getByText('Ansvarig nu')).toBeInTheDocument()
    expect(screen.getByText('Nästa steg')).toBeInTheDocument()
    expect(screen.getByText('Beslutad')).toBeInTheDocument()
  })

  it('renders all seven institutional steps by name', () => {
    renderCase(decided)
    for (const label of [
      'Tes formulerad',
      'Arbetet sammanvägt',
      'Faktagranskning',
      "Devil's Advocate",
      'Riskgranskning',
      'Inlämnad till CIO',
      'CIO-beslut',
    ]) {
      expect(screen.getAllByText(label).length).toBeGreaterThan(0)
    }
  })

  it('renders thesis, contributions, evidence and aggregation', () => {
    renderCase(decided)
    const fixture = asOverview(decided)

    expect(
      within(card(/^Tes \(/)).getByText(fixture.revisions[0]!.statement),
    ).toBeInTheDocument()
    expect(card(/^Bidrag \(/)).toBeInTheDocument()
    expect(card(/^Underlag \(/)).toBeInTheDocument()
    expect(card(/^Sammanvägning \(/)).toBeInTheDocument()

    /* The counts are real, not placeholders. */
    expect(
      screen.getByRole('heading', { name: `Bidrag (${fixture.claims.length})` }),
    ).toBeInTheDocument()
  })

  it('renders the three governance verdicts', () => {
    renderCase(decided)
    expect(card(/^Faktagranskning \(/)).toBeInTheDocument()
    expect(card(/^Devil's Advocate \(/)).toBeInTheDocument()
    expect(card(/^Risk \(/)).toBeInTheDocument()
  })

  it('renders the submission with the policy it was judged under', () => {
    renderCase(decided)
    const submissions = card(/^Inlämningar till CIO \(/)
    expect(within(submissions).getByText(/policy 1/)).toBeInTheDocument()
  })

  it('renders the decision, its author and its mandate', () => {
    renderCase(decided)
    const decision = card(/^Beslut$/)

    /*
     * The outcome as a label, not the raw code. `selected` is the firm's
     * identifier for the fact; "Position tagen" is what a person reads. The
     * code stays the identifier everywhere it travels — the mapping is the one
     * place it becomes Swedish.
     */
    expect(within(decision).getByText('Position tagen')).toBeInTheDocument()
    expect(within(decision).getByText(/cio/)).toBeInTheDocument()
    expect(within(decision).getByText(/chief-investment-officer/)).toBeInTheDocument()
  })

  it('renders the timeline with its actors', () => {
    renderCase(decided)
    const timeline = card(/^Händelseförlopp$/)
    const fixture = asOverview(decided)

    /* The movements a reader follows the case through. */
    expect(within(timeline).getAllByText(/review → decision/).length).toBeGreaterThan(0)
    expect(within(timeline).getAllByText(/decision → decided/).length).toBeGreaterThan(0)

    /* And every case movement names who moved it. */
    const movements = fixture.timeline.filter(
      (event) => event.subject === 'case' && event.fromState !== null,
    )
    expect(movements.length).toBeGreaterThan(0)
    for (const event of movements) {
      expect(event.actorEmployeeId).toBeTruthy()
      expect(
        within(timeline).getAllByText(event.actorEmployeeId!).length,
      ).toBeGreaterThan(0)
    }
  })
})

/* ------------------------------------------------------------------ dissent */

describe('dissent survives to the screen', () => {
  it('shows the objection, its weight, and the answer to it', () => {
    renderCase(decided)
    const decision = card(/^Beslut$/)

    expect(within(decision).getByText(/Kvarstående avvikande mening/)).toBeInTheDocument()
    expect(
      within(decision).getByText(/Fiskal impuls är inte prissatt/),
    ).toBeInTheDocument()
    expect(within(decision).getByText('devils-advocate:')).toBeInTheDocument()

    /*
     * The acknowledgement is the field the domain calls the one that matters —
     * the CIO saying in writing why they decided anyway. An objection rendered
     * without it leaves a reader believing nobody answered it.
     */
    expect(within(decision).getByText(/Bemötande:/)).toBeInTheDocument()
    expect(
      within(decision).getByText(/Risken är känd och accepterad/),
    ).toBeInTheDocument()
  })
})

/* -------------------------------------------------- the three eligibility states */

describe('the three eligibility states render distinctly', () => {
  it('shows a recorded verdict with the policy the basis names', () => {
    renderCase(decided)
    const panel = card(/^Beslutsunderlagets status$/)
    expect(within(panel).getByText('Uppfyllde kraven')).toBeInTheDocument()
    expect(within(panel).getByText(/Bedömt enligt policy 1/)).toBeInTheDocument()
  })

  it('shows "not submitted" as its own state, not as a failure', () => {
    renderCase(inflight)
    const panel = card(/^Beslutsunderlagets status$/)

    expect(within(panel).getByText('Inte inlämnad för beslut')).toBeInTheDocument()
    /* And says so in words, so it cannot be read as "did not qualify". */
    expect(
      within(panel).getByText(/inte samma sak som att kraven inte är uppfyllda/),
    ).toBeInTheDocument()
    /* No gate list at all: nothing has been judged. */
    expect(within(panel).queryByText('VERIFICATION_INCOMPLETE')).not.toBeInTheDocument()
  })

  it('shows an unreadable policy as a problem with the record', () => {
    /*
     * The only state no real case can currently produce — every stored basis
     * names policy 1, and the registry resolves it. Constructed from the union
     * rather than left unproved: it is the arm a reader is most likely to meet
     * years from now, and least likely to have been rendered before.
     */
    render(
      <CaseOverviewPage
        response={{
          ok: true,
          overview: {
            ...asOverview(decided),
            eligibility: { kind: 'policy-unresolvable', policyVersion: '99' },
          },
        }}
      />,
    )
    const panel = card(/^Beslutsunderlagets status$/)
    expect(within(panel).getByText(/Policy "99" kan inte läsas/)).toBeInTheDocument()
    expect(
      within(panel).getByText(/skulle vara ett utlåtande firman aldrig gjort/),
    ).toBeInTheDocument()
  })
})

/* ------------------------------------------- not-applicable is not a pass */

describe('not-applicable never renders as passed', () => {
  it('marks a Risk step the firm ruled unnecessary as its own state', () => {
    renderCase(noRisk)

    /*
     * From a real case: the position declared no implications, so the firm
     * resolved that Risk did not apply. Not a hand-edited status.
     */
    expect(screen.getByText('Ej tillämplig')).toBeInTheDocument()
    /* And it is not counted as done. */
    expect(screen.queryAllByText('Klart').length).toBeGreaterThan(0)
    expect(screen.getByText('Ej tillämplig')).not.toHaveTextContent('Klart')
  })

  it('gives the two states different marks, not only different colours', () => {
    const { container } = renderCase(noRisk)
    /*
     * Colour alone is no distinction for a reader who cannot see it, and these
     * two carry different obligations. Asserted through the icon element so a
     * future change to tone alone cannot collapse them.
     */
    const complete = container.querySelector('.text-positive')
    const notApplicable = container.querySelector('.text-content-muted')
    expect(complete).toBeTruthy()
    expect(notApplicable).toBeTruthy()
    expect(complete).not.toBe(notApplicable)
  })
})

/* ------------------------------------------------------------ ownership */

describe('ownership', () => {
  it('gives a settled case no current owner', () => {
    renderCase(decided)
    const standing = card(/^Ärendets ställning$/)

    /* The words, not a blank: an empty owner reads as missing data. */
    expect(within(standing).getByText('Ingen — ärendet är avgjort')).toBeInTheDocument()
    /*
     * "Inget utestående" appears twice on purpose — as the next act, and as the
     * step summary — so this counts rather than demanding uniqueness.
     */
    expect(within(standing).getAllByText(/Inget utestående/).length).toBe(2)
  })

  it('puts a submitted case on the chief’s desk, with a real next act', () => {
    renderCase(awaiting)
    expect(screen.getByText('cio')).toBeInTheDocument()
    expect(screen.getByText('Fatta beslut eller återsänd')).toBeInTheDocument()
    expect(screen.queryByText('Ingen — ärendet är avgjort')).not.toBeInTheDocument()
  })

  it('names the department that owes the next act while work is in flight', () => {
    renderCase(inflight)
    const standing = card(/^Ärendets ställning$/)

    expect(within(standing).getByText('Registrera faktagranskning')).toBeInTheDocument()
    /*
     * Scoped to the standing panel. `verification` also appears as a blocker's
     * owning department lower down, and matching either would not prove the
     * NEXT ACT names whose queue it is in.
     */
    expect(within(standing).getByText(/· verification/)).toBeInTheDocument()
  })
})

/* -------------------------------------- the non-material open challenge */

describe('a non-material open challenge', () => {
  it('is visible, and its gate is not a failure', () => {
    renderCase(decided)
    const fixture = asOverview(decided)

    /* Recorded and weighed, in the basis the CIO decided on. */
    const open = fixture.submissions[0]!.basis.devilsAdvocate!.openChallenges
    expect(open).toHaveLength(1)
    expect(open[0]!.materiality).toBe('non-material')

    /* And rendered as passed, under the policy the basis names. */
    const panel = card(/^Beslutsunderlagets status$/)
    const row = within(panel).getByText('CHALLENGE_UNRESOLVED').closest('li')!
    expect(within(row).getByText('Godkänd')).toBeInTheDocument()
    expect(within(row).queryByText('Ej uppfylld')).not.toBeInTheDocument()
  })

  it('shows the Devil’s Advocate section carrying the objection', () => {
    renderCase(decided)
    expect(
      within(card(/^Devil's Advocate \(/)).getByText(/1 invändningar/),
    ).toBeInTheDocument()
  })
})

/* --------------------------------------------------------- failure states */

describe('failures say what happened and nothing about how', () => {
  it('renders a missing case without leaking a code', () => {
    render(<CaseOverviewPage response={{ ok: false, code: 'NOT_FOUND' }} />)
    expect(screen.getByText('Ärendet finns inte.')).toBeInTheDocument()
    expect(screen.queryByText(/NOT_FOUND/)).not.toBeInTheDocument()
  })

  it('renders an unreachable runtime without leaking connection detail', () => {
    render(<CaseOverviewPage response={{ ok: false, code: 'SERVICE_UNAVAILABLE' }} />)
    expect(screen.getByText('Analysmiljön svarar inte just nu.')).toBeInTheDocument()
    expect(screen.queryByText(/postgres|SERVICE_UNAVAILABLE/)).not.toBeInTheDocument()
  })
})

/* ------------------------------------------------ the reconsideration loop */

describe('a case that was deferred, reopened and then decided', () => {
  it('renders all three acts as one history, in the order they happened', () => {
    renderCase(reconsidered)
    const history = card(/^Beslutshistorik/)

    /* Three acts on the decision boundary, not one live decision. */
    expect(within(history).getByText('Bordlagt')).toBeInTheDocument()
    expect(within(history).getByText('Återupptaget')).toBeInTheDocument()
    expect(within(history).getByText('Position tagen')).toBeInTheDocument()

    /*
     * In the order they happened, read from the rendered document rather than
     * from the data — a page can hold the right records and still show them
     * backwards.
     */
    const text = history.textContent ?? ''
    expect(text.indexOf('Bordlagt')).toBeLessThan(text.indexOf('Återupptaget'))
    expect(text.indexOf('Återupptaget')).toBeLessThan(text.indexOf('Position tagen'))
  })

  it('keeps the deferral’s own reasons and its conditions', () => {
    renderCase(reconsidered)
    const history = card(/^Beslutshistorik/)
    const fixture = asOverview(reconsidered)
    const deferral = fixture.decisionHistory.find(
      (decision) => decision.outcome.kind === 'deferred',
    )!

    /* The rationale the CIO gave for waiting. */
    expect(within(history).getByText(deferral.rationale)).toBeInTheDocument()

    /* And what would end the wait — the whole point of a deferral. */
    expect(within(history).getByText('Villkor för omprövning')).toBeInTheDocument()
    expect(within(history).getByText(/June staff projections/)).toBeInTheDocument()
  })

  it('says why the case came back', () => {
    renderCase(reconsidered)
    const history = card(/^Beslutshistorik/)

    expect(within(history).getByText('Villkor som uppfylldes')).toBeInTheDocument()
    expect(within(history).getByText(/June projections published/)).toBeInTheDocument()
    /* And who reopened it, under what mandate. */
    expect(within(history).getAllByText(/cio/).length).toBeGreaterThan(0)
  })

  it('shows the superseded deferral as a real act, not a correction', () => {
    renderCase(reconsidered)
    const history = card(/^Beslutshistorik/)

    /*
     * Said in words. Striking the text out would read as a mistake being
     * fixed, and the firm did decide to wait — it stayed decided until a
     * condition ended it.
     */
    expect(within(history).getByText('Ersatt av ett senare beslut')).toBeInTheDocument()
    expect(history.querySelector('s, del, .line-through')).toBeNull()
  })

  it('shows no new governance verdict was created for the unchanged revision', () => {
    renderCase(reconsidered)
    const fixture = asOverview(reconsidered)

    /*
     * One of each, for one revision, across the whole loop. A reopening that
     * had re-run governance would show more — and the page would be describing
     * work the firm never did.
     */
    expect(
      screen.getByRole('heading', {
        name: `Faktagranskning (${fixture.verification.length})`,
      }),
    ).toBeInTheDocument()
    expect(fixture.verification).toHaveLength(1)
    expect(fixture.devilsAdvocate).toHaveLength(1)
    expect(fixture.risk).toHaveLength(1)

    /* And every one of them belongs to the revision that was reconsidered. */
    const revisionId = fixture.reconsiderations[0]!.revisionId
    for (const review of [
      ...fixture.verification,
      ...fixture.devilsAdvocate,
      ...fixture.risk,
    ]) {
      expect(review.revisionId).toBe(revisionId)
    }
  })

  it('renders the reopening in the timeline as a case movement', () => {
    renderCase(reconsidered)
    const timeline = card(/^Händelseförlopp$/)

    expect(within(timeline).getAllByText(/decision → deferred/).length).toBeGreaterThan(0)
    expect(within(timeline).getAllByText(/deferred → decision/).length).toBeGreaterThan(0)
    expect(within(timeline).getAllByText(/decision → decided/).length).toBeGreaterThan(0)
  })
})
