/**
 * The Judgment surface, rendered against real work from a real firm.
 *
 * Three fixtures, generated by `runReview.pg.test.ts` from PostgreSQL: work
 * awaiting a decision, work that was accepted, and work that was declined. The
 * page has to read differently in all three, because a person arriving at it
 * has a different job in each.
 *
 * The rule this surface is held to, beyond the usual one: **produced work must
 * never read as the firm's position.** A reviewer who mistook unaccepted claims
 * for the institutional record would be judging something they believed was
 * already decided, and the entire acceptance boundary would have been built for
 * a screen that quietly undoes it.
 */

import { render, screen, within } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import {
  RouterProvider,
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
} from '@tanstack/react-router'
import type { ReactNode } from 'react'
import { RunReviewPage } from './runs.$runId'
import awaitingFixture from '~/test/fixtures/runReview.awaiting.json'
import acceptedFixture from '~/test/fixtures/runReview.accepted.json'
import rejectedFixture from '~/test/fixtures/runReview.rejected.json'
import operatorFixture from '~/test/fixtures/operatorIdentities.json'
import type { RunReview } from '~/application/analysis/runReview'
import type { OperatorIdentity } from '~/application/analysis/operatorIdentity'
import type { RunReviewResponse } from '~/infrastructure/analysis/serverFns'

const awaiting = awaitingFixture as unknown as RunReview
const accepted = acceptedFixture as unknown as RunReview
const rejected = rejectedFixture as unknown as RunReview
const identities = operatorFixture as unknown as readonly OperatorIdentity[]

async function withRouter(ui: ReactNode) {
  const rootRoute = createRootRoute({ component: () => <>{ui}</> })
  const children = [
    createRoute({
      getParentRoute: () => rootRoute,
      path: '/agents/$departmentId',
      component: () => null,
    }),
    createRoute({
      getParentRoute: () => rootRoute,
      path: '/cases/$caseId',
      component: () => null,
    }),
  ]
  const router = createRouter({
    routeTree: rootRoute.addChildren(children),
    history: createMemoryHistory({ initialEntries: ['/'] }),
  })
  await router.load()
  /* eslint-disable-next-line @typescript-eslint/no-explicit-any -- a test tree, not the app's */
  return render(<RouterProvider router={router as any} />)
}

const renderReview = (review: RunReview = awaiting) =>
  withRouter(
    <RunReviewPage
      review={{ ok: true, review }}
      operators={{ ok: true, identities }}
    />,
  )

describe('a reviewer sees what the agent actually produced', () => {
  it('leads with the question the firm asked and the desk that answered', async () => {
    await renderReview()
    expect(
      screen.getByRole('heading', { name: awaiting.investmentCase.question }),
    ).toBeInTheDocument()
    /*
     * The subtitle specifically. "Global Macro" also appears in the operator
     * list and in the ownership sentence — three true statements about the same
     * desk, and the header is the one this assertion is about.
     */
    expect(
      screen.getByText(`${awaiting.investmentCase.subject.displayName} · Global Macro`),
    ).toBeInTheDocument()
  })

  it('shows the brief the desk was given', async () => {
    await renderReview()
    expect(screen.getByText(awaiting.assignment!.brief)).toBeInTheDocument()
  })

  it('states the claim itself, not a summary of it', async () => {
    await renderReview()
    expect(
      screen.getByText(awaiting.produced[0]!.claim.statement),
    ).toBeInTheDocument()
  })

  it('shows the evidence the claim cites, with its source and quality', async () => {
    await renderReview()
    /* The provenance a reviewer judges the claim against — never reconstructed. */
    expect(screen.getByText('ECB')).toBeInTheDocument()
    expect(screen.getByText('Centralbank')).toBeInTheDocument()
    expect(screen.getByText('Officiell dagsnotering')).toBeInTheDocument()
    expect(screen.getByText('Underlaget stämmer')).toBeInTheDocument()
  })

  it('renders confidence with its recorded basis, verbatim', async () => {
    await renderReview()
    expect(screen.getByText('Måttlig tillförlitlighet')).toBeInTheDocument()
    /*
     * The firm's own recorded wording, not a translation. A second phrasing here
     * would give a reader two versions of one judgement.
     */
    for (const line of awaiting.produced[0]!.claim.confidence.basis) {
      expect(screen.getByText(line)).toBeInTheDocument()
    }
  })

  it('says when a confidence level is the model’s word rather than the firm’s', async () => {
    await renderReview()
    /* TD-75 made visible: four of seven signals have no institutional definition. */
    expect(
      screen.getByText('Modellens förslag — inte oberoende bekräftat av firman'),
    ).toBeInTheDocument()
  })
})

describe('produced work never reads as the institutional record', () => {
  it('says in plain words that nothing here is the firm’s position yet', async () => {
    await renderReview()
    expect(screen.getByText(/producerat arbete/)).toBeInTheDocument()
    expect(
      screen.getByText(/kan varken granskas, ifrågasättas eller åberopas/),
    ).toBeInTheDocument()
  })

  it('explains what each of the two acts does before offering them', async () => {
    await renderReview()
    const panel = screen.getByRole('heading', { name: 'Ditt beslut' }).closest('section')!
    expect(within(panel).getByText(/blir påståendena/)).toBeInTheDocument()
    expect(within(panel).getByText(/utan möjlighet att åberopas/)).toBeInTheDocument()
  })
})

describe('acting as somebody is operator identity, and says so', () => {
  it('labels the selection as not being a login', async () => {
    await renderReview()
    expect(screen.getByText('Operatörsidentitet — inte inloggning')).toBeInTheDocument()
    expect(
      screen.getByText(/Systemet kontrollerar inte att du är den personen/),
    ).toBeInTheDocument()
  })

  it('offers every employee of the firm, unfiltered', async () => {
    await renderReview()
    const select = screen.getByLabelText('Du agerar som')
    /* Every identity plus the empty placeholder. */
    expect(within(select).getAllByRole('option')).toHaveLength(identities.length + 1)
  })

  it('names the desk that owns the work as a fact, not as a filter', async () => {
    await renderReview()
    expect(screen.getByText(/Det här arbetet ägs av Global Macro/)).toBeInTheDocument()
  })

  it('will not let an act be signed by nobody', async () => {
    await renderReview()
    /* Both acts are unavailable until an operator is chosen. */
    expect(screen.getByRole('button', { name: 'Godkänn arbetet' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Avvisa arbetet' })).toBeDisabled()
    expect(screen.getByText('Välj vem du agerar som först.')).toBeInTheDocument()
  })
})

describe('rejection asks for both halves of the record', () => {
  it('offers exactly the firm’s six reason codes', async () => {
    await renderReview()
    const select = screen.getByLabelText('Avvisa — vad var fel?')
    expect(within(select).getAllByRole('option')).toHaveLength(6)
  })

  it('requires prose beside the code', async () => {
    await renderReview()
    const detail = screen.getByLabelText('Motivering')
    expect(detail).toBeRequired()
    expect(screen.getByText(/Motiveringen är det ingen kod kan bära/)).toBeInTheDocument()
  })
})

describe('work that has already been judged', () => {
  it('reports an acceptance as institutional, and offers no decision', async () => {
    await renderReview(accepted)
    expect(screen.getByRole('heading', { name: 'Beslutat' })).toBeInTheDocument()
    expect(screen.getByText(/kan åberopas i ärendets beslutsunderlag/)).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Godkänn arbetet' })).not.toBeInTheDocument()
  })

  it('keeps a rejection’s code, its prose and who declined it', async () => {
    await renderReview(rejected)
    expect(screen.getByText('Går längre än underlaget visar')).toBeInTheDocument()
    expect(screen.getByText(rejected.run.rejection!.detail)).toBeInTheDocument()
    expect(screen.getByText(/Avvisat av macro-head/)).toBeInTheDocument()
  })

  it('says declined work can never be cited, and still shows it', async () => {
    await renderReview(rejected)
    expect(
      screen.getByText(/finns kvar som historik och kan aldrig åberopas/),
    ).toBeInTheDocument()
    /* The work itself is still on the page — that is what durable history means. */
    expect(screen.getByText(rejected.produced[0]!.claim.statement)).toBeInTheDocument()
  })

  it('offers no decision on work nobody can judge any more', async () => {
    await renderReview(rejected)
    expect(screen.queryByRole('button', { name: 'Avvisa arbetet' })).not.toBeInTheDocument()
  })
})

describe('the failed states', () => {
  it('renders a missing run as a sentence, never as a code', async () => {
    await withRouter(
      <RunReviewPage
        review={{ ok: false, code: 'NOT_FOUND' } as RunReviewResponse}
        operators={{ ok: true, identities }}
      />,
    )
    expect(screen.getByText('Körningen finns inte.')).toBeInTheDocument()
    expect(screen.queryByText(/NOT_FOUND/)).not.toBeInTheDocument()
  })

  it('refuses to offer a decision when the employee registry cannot be read', async () => {
    await withRouter(
      <RunReviewPage
        review={{ ok: true, review: awaiting }}
        operators={{ ok: false, code: 'SERVICE_UNAVAILABLE' }}
      />,
    )
    /*
     * No operator list means no act can be booked against a named person, and
     * an act nobody is accountable for is the one thing this boundary refuses.
     */
    expect(
      screen.getByText(/ingen handling kan bokföras på en namngiven person/),
    ).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Godkänn arbetet' })).not.toBeInTheDocument()
  })
})
