/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as HeadquartersRouteImport } from './routes/headquarters'
import { Route as MarketImpactRouteImport } from './routes/market-impact'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SentinelRouteImport } from './routes/sentinel'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TodayRouteImport } from './routes/today'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsDepartmentIdRouteImport } from './routes/agents.$departmentId'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ClientsFormerRouteImport } from './routes/clients.former'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ClientsOnboardingRouteImport } from './routes/clients.onboarding'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as AgentsDepartmentIdCommissionRouteImport } from './routes/agents_.$departmentId.commission'
import { Route as CasesCaseIdUnderlagRouteImport } from './routes/cases.$caseId_.underlag'
import { Route as ClientsClientIdMeetingPackRouteImport } from './routes/clients.$clientId_.meeting-pack'
import { Route as ClientsClientIdMeetingPrepRouteImport } from './routes/clients.$clientId_.meeting-prep'
import { Route as ClientsOfficeOfficeIdRouteImport } from './routes/clients.office.$officeId'
import { Route as ClientsOfficeNewRouteImport } from './routes/clients.office.new'
import { Route as ClientsOfficesArchivedRouteImport } from './routes/clients.offices.archived'
import { Route as TodayCallClientIdRouteImport } from './routes/today_.call.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadquartersRoute = HeadquartersRouteImport.update({
  id: '/headquarters',
  path: '/headquarters',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketImpactRoute = MarketImpactRouteImport.update({
  id: '/market-impact',
  path: '/market-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SentinelRoute = SentinelRouteImport.update({
  id: '/sentinel',
  path: '/sentinel',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDepartmentIdRoute = AgentsDepartmentIdRouteImport.update({
  id: '/agents/$departmentId',
  path: '/agents/$departmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsFormerRoute = ClientsFormerRouteImport.update({
  id: '/clients/former',
  path: '/clients/former',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsOnboardingRoute = ClientsOnboardingRouteImport.update({
  id: '/clients/onboarding',
  path: '/clients/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDepartmentIdCommissionRoute =
  AgentsDepartmentIdCommissionRouteImport.update({
    id: '/agents_/$departmentId/commission',
    path: '/agents/$departmentId/commission',
    getParentRoute: () => rootRouteImport,
  } as any)
const CasesCaseIdUnderlagRoute = CasesCaseIdUnderlagRouteImport.update({
  id: '/cases/$caseId_/underlag',
  path: '/cases/$caseId/underlag',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdMeetingPackRoute =
  ClientsClientIdMeetingPackRouteImport.update({
    id: '/clients/$clientId_/meeting-pack',
    path: '/clients/$clientId/meeting-pack',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientsClientIdMeetingPrepRoute =
  ClientsClientIdMeetingPrepRouteImport.update({
    id: '/clients/$clientId_/meeting-prep',
    path: '/clients/$clientId/meeting-prep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientsOfficeOfficeIdRoute = ClientsOfficeOfficeIdRouteImport.update({
  id: '/clients/office/$officeId',
  path: '/clients/office/$officeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsOfficeNewRoute = ClientsOfficeNewRouteImport.update({
  id: '/clients/office/new',
  path: '/clients/office/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsOfficesArchivedRoute = ClientsOfficesArchivedRouteImport.update({
  id: '/clients/offices/archived',
  path: '/clients/offices/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayCallClientIdRoute = TodayCallClientIdRouteImport.update({
  id: '/today_/call/$clientId',
  path: '/today/call/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/headquarters': typeof HeadquartersRoute
  '/market-impact': typeof MarketImpactRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/sentinel': typeof SentinelRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/today': typeof TodayRoute
  '/watchlist': typeof WatchlistRoute
  '/agents/$departmentId': typeof AgentsDepartmentIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/former': typeof ClientsFormerRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients/onboarding': typeof ClientsOnboardingRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/agents/$departmentId/commission': typeof AgentsDepartmentIdCommissionRoute
  '/cases/$caseId/underlag': typeof CasesCaseIdUnderlagRoute
  '/clients/$clientId/meeting-pack': typeof ClientsClientIdMeetingPackRoute
  '/clients/$clientId/meeting-prep': typeof ClientsClientIdMeetingPrepRoute
  '/clients/office/$officeId': typeof ClientsOfficeOfficeIdRoute
  '/clients/office/new': typeof ClientsOfficeNewRoute
  '/clients/offices/archived': typeof ClientsOfficesArchivedRoute
  '/today/call/$clientId': typeof TodayCallClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/headquarters': typeof HeadquartersRoute
  '/market-impact': typeof MarketImpactRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/sentinel': typeof SentinelRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/today': typeof TodayRoute
  '/watchlist': typeof WatchlistRoute
  '/agents/$departmentId': typeof AgentsDepartmentIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/former': typeof ClientsFormerRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients/onboarding': typeof ClientsOnboardingRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/agents': typeof AgentsIndexRoute
  '/cases': typeof CasesIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/agents/$departmentId/commission': typeof AgentsDepartmentIdCommissionRoute
  '/cases/$caseId/underlag': typeof CasesCaseIdUnderlagRoute
  '/clients/$clientId/meeting-pack': typeof ClientsClientIdMeetingPackRoute
  '/clients/$clientId/meeting-prep': typeof ClientsClientIdMeetingPrepRoute
  '/clients/office/$officeId': typeof ClientsOfficeOfficeIdRoute
  '/clients/office/new': typeof ClientsOfficeNewRoute
  '/clients/offices/archived': typeof ClientsOfficesArchivedRoute
  '/today/call/$clientId': typeof TodayCallClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/headquarters': typeof HeadquartersRoute
  '/market-impact': typeof MarketImpactRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/sentinel': typeof SentinelRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/today': typeof TodayRoute
  '/watchlist': typeof WatchlistRoute
  '/agents/$departmentId': typeof AgentsDepartmentIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/former': typeof ClientsFormerRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients/onboarding': typeof ClientsOnboardingRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/agents_/$departmentId/commission': typeof AgentsDepartmentIdCommissionRoute
  '/cases/$caseId_/underlag': typeof CasesCaseIdUnderlagRoute
  '/clients/$clientId_/meeting-pack': typeof ClientsClientIdMeetingPackRoute
  '/clients/$clientId_/meeting-prep': typeof ClientsClientIdMeetingPrepRoute
  '/clients/office/$officeId': typeof ClientsOfficeOfficeIdRoute
  '/clients/office/new': typeof ClientsOfficeNewRoute
  '/clients/offices/archived': typeof ClientsOfficesArchivedRoute
  '/today_/call/$clientId': typeof TodayCallClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evidence'
    | '/headquarters'
    | '/market-impact'
    | '/markets'
    | '/portfolio'
    | '/recovery'
    | '/reports'
    | '/sentinel'
    | '/settings'
    | '/setup'
    | '/today'
    | '/watchlist'
    | '/agents/$departmentId'
    | '/cases/$caseId'
    | '/clients/$clientId'
    | '/clients/former'
    | '/clients/new'
    | '/clients/onboarding'
    | '/runs/$runId'
    | '/agents/'
    | '/cases/'
    | '/clients/'
    | '/agents/$departmentId/commission'
    | '/cases/$caseId/underlag'
    | '/clients/$clientId/meeting-pack'
    | '/clients/$clientId/meeting-prep'
    | '/clients/office/$officeId'
    | '/clients/office/new'
    | '/clients/offices/archived'
    | '/today/call/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evidence'
    | '/headquarters'
    | '/market-impact'
    | '/markets'
    | '/portfolio'
    | '/recovery'
    | '/reports'
    | '/sentinel'
    | '/settings'
    | '/setup'
    | '/today'
    | '/watchlist'
    | '/agents/$departmentId'
    | '/cases/$caseId'
    | '/clients/$clientId'
    | '/clients/former'
    | '/clients/new'
    | '/clients/onboarding'
    | '/runs/$runId'
    | '/agents'
    | '/cases'
    | '/clients'
    | '/agents/$departmentId/commission'
    | '/cases/$caseId/underlag'
    | '/clients/$clientId/meeting-pack'
    | '/clients/$clientId/meeting-prep'
    | '/clients/office/$officeId'
    | '/clients/office/new'
    | '/clients/offices/archived'
    | '/today/call/$clientId'
  id:
    | '__root__'
    | '/'
    | '/evidence'
    | '/headquarters'
    | '/market-impact'
    | '/markets'
    | '/portfolio'
    | '/recovery'
    | '/reports'
    | '/sentinel'
    | '/settings'
    | '/setup'
    | '/today'
    | '/watchlist'
    | '/agents/$departmentId'
    | '/cases/$caseId'
    | '/clients/$clientId'
    | '/clients/former'
    | '/clients/new'
    | '/clients/onboarding'
    | '/runs/$runId'
    | '/agents/'
    | '/cases/'
    | '/clients/'
    | '/agents_/$departmentId/commission'
    | '/cases/$caseId_/underlag'
    | '/clients/$clientId_/meeting-pack'
    | '/clients/$clientId_/meeting-prep'
    | '/clients/office/$officeId'
    | '/clients/office/new'
    | '/clients/offices/archived'
    | '/today_/call/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceRoute: typeof EvidenceRoute
  HeadquartersRoute: typeof HeadquartersRoute
  MarketImpactRoute: typeof MarketImpactRoute
  MarketsRoute: typeof MarketsRoute
  PortfolioRoute: typeof PortfolioRoute
  RecoveryRoute: typeof RecoveryRoute
  ReportsRoute: typeof ReportsRoute
  SentinelRoute: typeof SentinelRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TodayRoute: typeof TodayRoute
  WatchlistRoute: typeof WatchlistRoute
  AgentsDepartmentIdRoute: typeof AgentsDepartmentIdRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsFormerRoute: typeof ClientsFormerRoute
  ClientsNewRoute: typeof ClientsNewRoute
  ClientsOnboardingRoute: typeof ClientsOnboardingRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  CasesIndexRoute: typeof CasesIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  AgentsDepartmentIdCommissionRoute: typeof AgentsDepartmentIdCommissionRoute
  CasesCaseIdUnderlagRoute: typeof CasesCaseIdUnderlagRoute
  ClientsClientIdMeetingPackRoute: typeof ClientsClientIdMeetingPackRoute
  ClientsClientIdMeetingPrepRoute: typeof ClientsClientIdMeetingPrepRoute
  ClientsOfficeOfficeIdRoute: typeof ClientsOfficeOfficeIdRoute
  ClientsOfficeNewRoute: typeof ClientsOfficeNewRoute
  ClientsOfficesArchivedRoute: typeof ClientsOfficesArchivedRoute
  TodayCallClientIdRoute: typeof TodayCallClientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headquarters': {
      id: '/headquarters'
      path: '/headquarters'
      fullPath: '/headquarters'
      preLoaderRoute: typeof HeadquartersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-impact': {
      id: '/market-impact'
      path: '/market-impact'
      fullPath: '/market-impact'
      preLoaderRoute: typeof MarketImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentinel': {
      id: '/sentinel'
      path: '/sentinel'
      fullPath: '/sentinel'
      preLoaderRoute: typeof SentinelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$departmentId': {
      id: '/agents/$departmentId'
      path: '/agents/$departmentId'
      fullPath: '/agents/$departmentId'
      preLoaderRoute: typeof AgentsDepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/former': {
      id: '/clients/former'
      path: '/clients/former'
      fullPath: '/clients/former'
      preLoaderRoute: typeof ClientsFormerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/onboarding': {
      id: '/clients/onboarding'
      path: '/clients/onboarding'
      fullPath: '/clients/onboarding'
      preLoaderRoute: typeof ClientsOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents_/$departmentId/commission': {
      id: '/agents_/$departmentId/commission'
      path: '/agents/$departmentId/commission'
      fullPath: '/agents/$departmentId/commission'
      preLoaderRoute: typeof AgentsDepartmentIdCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId_/underlag': {
      id: '/cases/$caseId_/underlag'
      path: '/cases/$caseId/underlag'
      fullPath: '/cases/$caseId/underlag'
      preLoaderRoute: typeof CasesCaseIdUnderlagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId_/meeting-pack': {
      id: '/clients/$clientId_/meeting-pack'
      path: '/clients/$clientId/meeting-pack'
      fullPath: '/clients/$clientId/meeting-pack'
      preLoaderRoute: typeof ClientsClientIdMeetingPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId_/meeting-prep': {
      id: '/clients/$clientId_/meeting-prep'
      path: '/clients/$clientId/meeting-prep'
      fullPath: '/clients/$clientId/meeting-prep'
      preLoaderRoute: typeof ClientsClientIdMeetingPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/office/$officeId': {
      id: '/clients/office/$officeId'
      path: '/clients/office/$officeId'
      fullPath: '/clients/office/$officeId'
      preLoaderRoute: typeof ClientsOfficeOfficeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/office/new': {
      id: '/clients/office/new'
      path: '/clients/office/new'
      fullPath: '/clients/office/new'
      preLoaderRoute: typeof ClientsOfficeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/offices/archived': {
      id: '/clients/offices/archived'
      path: '/clients/offices/archived'
      fullPath: '/clients/offices/archived'
      preLoaderRoute: typeof ClientsOfficesArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today_/call/$clientId': {
      id: '/today_/call/$clientId'
      path: '/today/call/$clientId'
      fullPath: '/today/call/$clientId'
      preLoaderRoute: typeof TodayCallClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceRoute: EvidenceRoute,
  HeadquartersRoute: HeadquartersRoute,
  MarketImpactRoute: MarketImpactRoute,
  MarketsRoute: MarketsRoute,
  PortfolioRoute: PortfolioRoute,
  RecoveryRoute: RecoveryRoute,
  ReportsRoute: ReportsRoute,
  SentinelRoute: SentinelRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TodayRoute: TodayRoute,
  WatchlistRoute: WatchlistRoute,
  AgentsDepartmentIdRoute: AgentsDepartmentIdRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsFormerRoute: ClientsFormerRoute,
  ClientsNewRoute: ClientsNewRoute,
  ClientsOnboardingRoute: ClientsOnboardingRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  CasesIndexRoute: CasesIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  AgentsDepartmentIdCommissionRoute: AgentsDepartmentIdCommissionRoute,
  CasesCaseIdUnderlagRoute: CasesCaseIdUnderlagRoute,
  ClientsClientIdMeetingPackRoute: ClientsClientIdMeetingPackRoute,
  ClientsClientIdMeetingPrepRoute: ClientsClientIdMeetingPrepRoute,
  ClientsOfficeOfficeIdRoute: ClientsOfficeOfficeIdRoute,
  ClientsOfficeNewRoute: ClientsOfficeNewRoute,
  ClientsOfficesArchivedRoute: ClientsOfficesArchivedRoute,
  TodayCallClientIdRoute: TodayCallClientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
