/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsDepartmentIdRouteImport } from './routes/agents.$departmentId'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as AgentsDepartmentIdCommissionRouteImport } from './routes/agents_.$departmentId.commission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDepartmentIdRoute = AgentsDepartmentIdRouteImport.update({
  id: '/agents/$departmentId',
  path: '/agents/$departmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDepartmentIdCommissionRoute =
  AgentsDepartmentIdCommissionRouteImport.update({
    id: '/agents_/$departmentId/commission',
    path: '/agents/$departmentId/commission',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/agents/$departmentId': typeof AgentsDepartmentIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/agents/$departmentId/commission': typeof AgentsDepartmentIdCommissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/agents/$departmentId': typeof AgentsDepartmentIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/agents': typeof AgentsIndexRoute
  '/cases': typeof CasesIndexRoute
  '/agents/$departmentId/commission': typeof AgentsDepartmentIdCommissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/agents/$departmentId': typeof AgentsDepartmentIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/agents_/$departmentId/commission': typeof AgentsDepartmentIdCommissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evidence'
    | '/markets'
    | '/portfolio'
    | '/reports'
    | '/settings'
    | '/watchlist'
    | '/agents/$departmentId'
    | '/cases/$caseId'
    | '/runs/$runId'
    | '/agents/'
    | '/cases/'
    | '/agents/$departmentId/commission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evidence'
    | '/markets'
    | '/portfolio'
    | '/reports'
    | '/settings'
    | '/watchlist'
    | '/agents/$departmentId'
    | '/cases/$caseId'
    | '/runs/$runId'
    | '/agents'
    | '/cases'
    | '/agents/$departmentId/commission'
  id:
    | '__root__'
    | '/'
    | '/evidence'
    | '/markets'
    | '/portfolio'
    | '/reports'
    | '/settings'
    | '/watchlist'
    | '/agents/$departmentId'
    | '/cases/$caseId'
    | '/runs/$runId'
    | '/agents/'
    | '/cases/'
    | '/agents_/$departmentId/commission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceRoute: typeof EvidenceRoute
  MarketsRoute: typeof MarketsRoute
  PortfolioRoute: typeof PortfolioRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  WatchlistRoute: typeof WatchlistRoute
  AgentsDepartmentIdRoute: typeof AgentsDepartmentIdRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  CasesIndexRoute: typeof CasesIndexRoute
  AgentsDepartmentIdCommissionRoute: typeof AgentsDepartmentIdCommissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$departmentId': {
      id: '/agents/$departmentId'
      path: '/agents/$departmentId'
      fullPath: '/agents/$departmentId'
      preLoaderRoute: typeof AgentsDepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents_/$departmentId/commission': {
      id: '/agents_/$departmentId/commission'
      path: '/agents/$departmentId/commission'
      fullPath: '/agents/$departmentId/commission'
      preLoaderRoute: typeof AgentsDepartmentIdCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceRoute: EvidenceRoute,
  MarketsRoute: MarketsRoute,
  PortfolioRoute: PortfolioRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  WatchlistRoute: WatchlistRoute,
  AgentsDepartmentIdRoute: AgentsDepartmentIdRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  CasesIndexRoute: CasesIndexRoute,
  AgentsDepartmentIdCommissionRoute: AgentsDepartmentIdCommissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
